name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-artifacts:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Fetch
        run: git fetch --force --tags

      - name: Setup Problem Matcher
        uses: Joshua-Ashton/gcc-problem-matcher@v1

      - name: Install Dependencies
        run: |
          brew install coreutils
          brew install meson
          brew install mingw-w64
          brew install glslang

      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v5
      
      - name: Create Version Name
        run: |
          export VERSION_NAME="${{ steps.branch-name.outputs.current_branch }}-"
          export VERSION_NAME="${VERSION_NAME}-$(git describe)"
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Build
        run: ./package-release.sh "${env.VERSION_NAME}" build --no-package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxvk-${{ env.VERSION_NAME }}
          path: build/dxvk-${{ env.VERSION_NAME }}
          if-no-files-found: error
