name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-artifacts:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Fetch
        run: git fetch --force --tags

      - name: Setup Problem Matcher
        uses: Joshua-Ashton/gcc-problem-matcher@v1

      - name: Install Dependencies
        run: |
          brew install coreutils
          brew install meson
          brew install mingw-w64
          brew install glslang

      - name: Get Branch Name
        id: branch_name
        uses: tj-actions/branch-names@v5
      
      - name: Create Version Name
        id: version_name
        run: |
          export VERSION_NAME="${{ steps.branch_name.outputs.current_branch }}"
          export VERSION_NAME="${VERSION_NAME}-$(git describe)"
          echo "::set-output name=name::${VERSION_NAME}\n"

      - name: Build
        run: ./package-release.sh ${{ steps.version_name.outputs.name }} build --no-package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxvk-${{ steps.version_name.outputs.name }}
          path: build/dxvk-${{ steps.version_name.outputs.name }}
          if-no-files-found: error
